/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'tertiary-fixed-dim': '#7bd0ff',
        'surface-container': '#1a202c',
        'on-error-container': '#ffdad6',
        'on-secondary-container': '#00452e',
        'on-tertiary-fixed': '#001e2c',
        'secondary-fixed': '#68fcbf',
        'surface-dim': '#0d131f',
        'tertiary-container': '#19aee8',
        'primary-fixed-dim': '#4edea3',
        'on-background': '#f8fafc',
        'inverse-surface': '#dde2f3',
        'on-error': '#690005',
        'tertiary-fixed': '#c4e7ff',
        background: '#0d131f',
        'on-primary-fixed': '#002113',
        'secondary-fixed-dim': '#45dfa4',
        'inverse-primary': '#006c49',
        'surface-container-high': '#242a37',
        'on-primary-fixed-variant': '#005236',
        'on-surface': '#f8fafc',
        'primary-fixed': '#6ffbbe',
        'surface-bright': '#333946',
        'surface-container-lowest': '#080e1a',
        'on-secondary': '#003825',
        'error-container': '#93000a',
        'inverse-on-surface': '#2a303d',
        'surface-container-highest': '#2f3542',
        'surface-container-low': '#161c28',
        'on-secondary-fixed': '#002114',
        surface: '#0d131f',
        tertiary: '#7bd0ff',
        error: '#f87171',
        'on-tertiary': '#00354a',
        'on-secondary-fixed-variant': '#005137',
        'on-tertiary-fixed-variant': '#004c69',
        'primary-container': '#10b981',
        'outline-variant': '#283245',
        'surface-variant': '#161c28',
        'on-tertiary-container': '#003e55',
        'on-surface-variant': '#94a3b8',
        'secondary-container': '#00bd85',
        secondary: '#45dfa4',
        'on-primary-container': '#00422b',
        'on-primary': '#003824',
        primary: '#10b981',
        'surface-tint': '#4edea3',
        outline: '#86948a',
        'sage-accent': '#10b981',
        'status-success': '#4ade80',
        'status-warning': '#fbbf24',
        'status-error': '#f87171',
        'border-hairline': '#283245',
        'surface-base': '#161c28',
        'surface-muted': '#1a202c',
        'cool-blue': '#38bdf8',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'space-sm': '0.5rem',
        gutter: '1.5rem',
        margin: '2rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xs': '0.25rem',
        'space-xl': '2.5rem',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        'body-md': ['Inter', 'system-ui', 'sans-serif'],
        'headline-sm': ['Inter', 'system-ui', 'sans-serif'],
        'headline-md': ['Inter', 'system-ui', 'sans-serif'],
        'headline-lg': ['Inter', 'system-ui', 'sans-serif'],
        'label-md': ['Inter', 'system-ui', 'sans-serif'],
        'label-sm': ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'headline-lg-mobile': [
          '22px',
          { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '600' },
        ],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': [
          '12px',
          { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '500' },
        ],
        'body-sm': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-lg': [
          '28px',
          { lineHeight: '36px', letterSpacing: '-0.01em', fontWeight: '600' },
        ],
        'headline-md': ['22px', { lineHeight: '28px', fontWeight: '500' }],
        'headline-xl-mobile': [
          '28px',
          { lineHeight: '34px', letterSpacing: '-0.02em', fontWeight: '600' },
        ],
        'headline-sm': ['18px', { lineHeight: '24px', fontWeight: '500' }],
        'label-sm': [
          '11px',
          { lineHeight: '14px', letterSpacing: '0.04em', fontWeight: '500' },
        ],
        'headline-xl': [
          '36px',
          { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '600' },
        ],
      },
    },
  },
  plugins: [],
}
